<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <Version>1.0.1</Version>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Analyzers\PgQuery.Analyzers.csproj" />
    <ProjectReference Include="..\DMLOpsAnalyzer\PgQuery.DMLOpsAnalyzer.csproj" />
  </ItemGroup>

</Project>
