<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<Authors>Dmitriy Manuylov</Authors>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PgQuery.Analyzers\PgQuery.Analyzers.csproj" />
    <ProjectReference Include="..\PgQuery.DMLOpsAnalyzer\PgQuery.DMLOpsAnalyzer.csproj" />
  </ItemGroup>

</Project>
